version: '3.8'

services:
  resume-analyzer:
    build:
      context: ./resume-analyzer
      dockerfile: Dockerfile
    container_name: careerbuddy_resume_analyzer
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - PYTHONPATH=/app
    volumes:
      - ./resume-analyzer:/app
      - /app/__pycache__
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  job-matcher:
    build:
      context: ./job-matcher
      dockerfile: Dockerfile
    container_name: careerbuddy_job_matcher
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - PYTHONPATH=/app
    volumes:
      - ./job-matcher:/app
      - /app/__pycache__
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  default:
    name: careerbuddy_ai_network
